### ISSUE TITLE
helm repo add svc-cat - is not a valid chart repository or cannot be reached

### ISSUE THREAD

**Issue by alexwo** [kubernetes-sigs/service-catalog#2868] opened 2020-12-23 07:45 UTC
# Bug Report 

**What happened**:

Running:
```
 helm repo add svc-cat https://svc-catalog-charts.storage.googleapis.com 
```

> looks like "https://svc-catalog-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: failed to fetch https://svc-catalog-charts.storage.googleapis.com/index.yaml : 403 Forbidden**

**How to reproduce it (as minimally and precisely as possible)**:
helm repo add svc-cat https://svc-catalog-charts.storage.googleapis.com

**Comment by jhvhs** [comment] 2021-01-10 13:38
Duplicate of #2869 
Documentation fixed in #2875

**Closed by jhvhs** 2021-01-10 13:38 UTC
