### ISSUE TITLE
Created Binding overwrites non-conflicting keys in existing credentials Secret

### ISSUE THREAD

**Issue by codevulture** [kubernetes-sigs/service-catalog#1968] opened 2018-04-23 15:37 UTC
I think Creating the bindings overwrites the existing secrets stored in k8s.

[azure wordpress](https://github.com/Azure/open-service-broker-azure/blob/master/docs/quickstart-minikube.md#deploy-wordpress)

Kindly check. Can be reproduced. Do not have logs currently, will update if needed.

[closed bug from azure and opened here](https://github.com/Azure/open-service-broker-azure/issues/404)

**Comment by jeremyrickard** [comment] 2018-04-23 16:12
Hey @codevulture. Could you provide a little more detail about what you're encountering exactly? I've re-opened your issue in the Open Service Broker for Azure repo. My statement is true, service catalog is the party that makes the secrets/etc in Kubernetes, but it could be that you're encountering an issue with the OBSA related helm chart. If you could include more detail about the issue you are seeing with output/etc, it would helpful in order to help triage the issue that you are seeing. We can continue to discuss it in the OSBA repo and bounce back over here once we've narrowed it down.

**Comment by MHBauer** [comment] 2018-04-25 15:56
We create or update the secret.
https://github.com/kubernetes-incubator/service-catalog/blob/master/pkg/controller/controller_binding.go#L449-L495
If there's a conflct on what the secret contains, it's an unfortunate circumstance, but svc-cat does allow you to specify a secret to create the bindings inside of. The user of the service must be aware of what keys are going to be created and possibly overwritten. SecretTransform might help if there are no changes that can be made, but I'm not sure how much more adjusting the service-catalog can do.

**Comment by n3wscott** [comment] 2018-04-27 15:25
this is something I have been thinking about, I wonder if there would be a way to mark the secret as being made as a result of a binding and which binding that was, in the terse bug report here the assumption is the binding was named something generic and conflicted with an existing secret... But perhaps we could detect the overwriting case if we knew who created that secret initially.

**Comment by nilebox** [comment] 2018-05-13 23:56
> I wonder if there would be a way to mark the secret as being made as a result of a binding and which binding that was

@n3wscott We already set and check `ownerReference` for that: https://github.com/kubernetes-incubator/service-catalog/blob/v0.1.15/pkg/controller/controller_binding.go#L454-L457

@codevulture do I understand correctly that you want to keep the non-conflicting Secret keys untouched instead of being erased? Otherwise overwriting the secret previously created by the same binding is by design. If there is an existing secret that wasn't created by the binding, the update will fail because of missing/different `ownerReference`, see link above.

**Comment by codevulture** [comment] 2018-05-14 03:33
> do I understand correctly that you want to keep the non-conflicting Secret keys untouched instead of being erased?
@nilebox : yes

**Comment by nilebox** [comment] 2018-05-14 03:42
@codevulture ok, I renamed the issue to better reflect the feature request.

**Comment by MHBauer** [comment] 2019-04-23 16:07
/assign @jberkhahn 

This is a low-priority bug. As I say above, it's defined that we overwrite things. Combined with the "I get the secrets exactly one time" it becomes an issue if we don't overwrite them, as it'll lose the creds.

**Comment by mrbobbytables** [comment] 2022-05-06 14:28
This project is being archived, closing open issues and PRs. 
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632

**Closed by mrbobbytables** 2022-05-06 14:28 UTC
Labels: lifecycle/frozen
