### ISSUE TITLE
deregister confusingly fails if missing --scope cluster

### ISSUE THREAD

**Issue by drnic** [kubernetes-sigs/service-catalog#2439] opened 2018-10-25 22:40 UTC
# Bug Report 

**What happened**:

```
$ svcat get brokers
                  NAME                   NAMESPACE                                      URL                                              STATUS
+--------------------------------------+-----------+----------------------------------------------------------------------------+----------------------+
  email-worlds-simplest-service-broker               http://email-worlds-simplest-service-broker.default.svc.cluster.local:3000   ErrorFetchingCatalog

$ svcat deregister email-worlds-simplest-service-broker
Error: deregister request failed (servicebrokers.servicecatalog.k8s.io "email-worlds-simplest-service-broker" not found)
```

I also cannot resync the broker if I think I've resolved an issue:

```
$ svcat sync broker email-worlds-simplest-service-broker
Error: could not sync service broker email-worlds-simplest-service-broker (unable to get broker 'email-worlds-simplest-service-broker' (servicebrokers.servicecatalog.k8s.io "email-worlds-simplest-service-broker" not found))
```

**What you expected to happen**:

That the broker was deregistered/CRDs deleted.

**Comment by carlory** [comment] 2018-10-31 15:41
@drnic which version of the `svcat` are you using?

**Comment by carlory** [comment] 2018-10-31 16:01
@drnic 

`email-worlds-simplest-service-broker` is a cluster broker.  

```shell
svcat deregister email-worlds-simplest-service-broker --scope cluster
```

This command can help you deregister it.

If you want to deregister a namespace broker, please using the following command

```shell
svcat deregister ups-broker --namespace ups-broker
```

**Comment by carlory** [comment] 2018-10-31 16:23
@carolynvs Is it a bug ?

**Comment by carolynvs** [comment] 2018-10-31 19:08
Sorry I should have left a comment when I labeled this a bug!

You are correct about the root cause of those commands failing, however our error messages should be fixed to suggest that they may be searching at the wrong scope as well. Otherwise I anticipate that this will be a common bug report going forward. 😀

**Comment by drnic** [comment] 2018-11-01 22:18
Thanks for pointing out I also need `--scope cluster` for deregister. It does seem slightly redundant as a user might assume that Service Catalog remembers where/how it had previously registered a service broker, and thus how to deregister it :)

The extra error message suggested is good. Is it also possible to make `--scope` unnecessary for `deregister`?

**Comment by drnic** [comment] 2019-05-26 20:34
Can we turn off the bots whilst this project is inactive?

**Closed** 2019-06-25 21:10 UTC
Labels: kind/bug, lifecycle/rotten, needs-help
